Fix `build:example` command for Netlify deploys
Context:

* Netlify upgraded to Ubuntu 20.
* `build:example` fails on Node version 18

Fix (band-aid):

Set NODE_OPTIONS to workaround `ERR_OSSL_EVP_UNSUPPORTED`

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/cwmanning/Sites/react-ink/node_modules/webpack/lib/util/createHash.js:75:53)
```